// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Hypar.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace IndViz
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    
    public  class IndVizInputs : ArgsBase
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public IndVizInputs(double @gigaWatts, double @constructionYear, bool @gableRoofAndMassOpacity, bool @footballFieldVisibility, bool @areaMassOpacity, bool @siteVisibility, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<IndVizInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @gigaWatts, @constructionYear, @gableRoofAndMassOpacity, @footballFieldVisibility, @areaMassOpacity, @siteVisibility});
            }
        
            this.GigaWatts = @gigaWatts;
            this.ConstructionYear = @constructionYear;
            this.GableRoofAndMassOpacity = @gableRoofAndMassOpacity;
            this.FootballFieldVisibility = @footballFieldVisibility;
            this.AreaMassOpacity = @areaMassOpacity;
            this.SiteVisibility = @siteVisibility;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>Production Capacity</summary>
        [Newtonsoft.Json.JsonProperty("GigaWatts", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(19D, 59D)]
        public double GigaWatts { get; set; } = 50D;
    
        /// <summary>Year the construction will begin to account for inflation ( 4%)</summary>
        [Newtonsoft.Json.JsonProperty("ConstructionYear", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(2025D, 2055D)]
        public double ConstructionYear { get; set; } = 2026D;
    
        /// <summary>Toggle between Ghosted and fully Opaque</summary>
        [Newtonsoft.Json.JsonProperty("GableRoofAndMassOpacity", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool GableRoofAndMassOpacity { get; set; } = false;
    
        /// <summary>Toggle between Ghosted and fully Opaque</summary>
        [Newtonsoft.Json.JsonProperty("FootballFieldVisibility", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool FootballFieldVisibility { get; set; } = false;
    
        /// <summary>Toggle between Ghosted and fully Opaque</summary>
        [Newtonsoft.Json.JsonProperty("AreaMassOpacity", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool AreaMassOpacity { get; set; } = false;
    
        [Newtonsoft.Json.JsonProperty("SiteVisibility", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool SiteVisibility { get; set; } = false;
    
    }
}